// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKwNjyobAJm2LCa1LZNOOsV_97KGScrJ0',
    appId: '1:570846591975:web:c5b7d750b8f9837727db42',
    messagingSenderId: '570846591975',
    projectId: 'musicgram-15d07',
    authDomain: 'musicgram-15d07.firebaseapp.com',
    storageBucket: 'musicgram-15d07.appspot.com',
    measurementId: 'G-ZDEQLE6337',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxU8tP0jDRFJfgTm19dblgXMEXIkT_ZQ',
    appId: '1:570846591975:android:1599a895dd2213c727db42',
    messagingSenderId: '570846591975',
    projectId: 'musicgram-15d07',
    storageBucket: 'musicgram-15d07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_rJHGwAkxuBmjrvt0CtdkH7ZZe0aIhos',
    appId: '1:570846591975:ios:04b23588f37f72ec27db42',
    messagingSenderId: '570846591975',
    projectId: 'musicgram-15d07',
    storageBucket: 'musicgram-15d07.appspot.com',
    iosBundleId: 'com.example.musicgram4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_rJHGwAkxuBmjrvt0CtdkH7ZZe0aIhos',
    appId: '1:570846591975:ios:04b23588f37f72ec27db42',
    messagingSenderId: '570846591975',
    projectId: 'musicgram-15d07',
    storageBucket: 'musicgram-15d07.appspot.com',
    iosBundleId: 'com.example.musicgram4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKwNjyobAJm2LCa1LZNOOsV_97KGScrJ0',
    appId: '1:570846591975:web:7b1a8e5dcffb73ea27db42',
    messagingSenderId: '570846591975',
    projectId: 'musicgram-15d07',
    authDomain: 'musicgram-15d07.firebaseapp.com',
    storageBucket: 'musicgram-15d07.appspot.com',
    measurementId: 'G-DWEWMLMRCF',
  );
}
